enum SiftIcon {
    static let home = "house"
    static let subscriptions = "rectangle.stack"
    static let insights = "chart.bar"
    static let transactions = "list.bullet.rectangle"
    static let profile = "person.crop.circle"
    static let bell = "bell"
    static let lock = "lock"
    static let gear = "gearshape"
    static let bank = "building.columns"
    static let privacy = "shield"
    static let card = "creditcard"
    static let arrowUp = "arrow.up"
    static let arrowDown = "arrow.down"
    static let check = "checkmark"
    static let chevronRight = "chevron.right"
    static let plus = "plus"
    static let externalLink = "arrow.up.right"
    static let list = "list.bullet"
    static let refresh = "arrow.clockwise"
    static let warning = "exclamationmark.triangle"
    static let calendar = "calendar"
    static let support = "envelope"
}
